## Jupyter notebook

* 파이썬은 매우 간결한 언어
* 사람의 언어에 가장 가까운 언어
* 적당히 빠른 속도
* 다양한 통계 모듈
* 다양한 시각화 모듈
* 통계분석 - 게임제작 - 웹개발 - 어플리케이션 개발 
* 기계학습 및 인공지능 기반 분석
* Jupyter 는 파이썬을 대화창 형식으로 coding 할 수 있게 해주는 툴
* 전세계적으로 본인의 연구 결과를 Jupyter로 올리는 사람이 늘어나고 있음 

https://repo.continuum.io/archive/



---

In [12]:
## 변수에 문자를 할당
a = "babo"
## 변수에 숫자를 할당
b = 2018
## 숫자처럼 보여도 문자를 할당
c = "2018"

In [13]:
a,b,c

('babo', 2018, '2018')

In [14]:
type(a),type(b),type(c)

(str, int, str)

In [56]:
#숫자는 연산이 된다.
i = 1

In [57]:
i = i + 3

In [58]:
i

4

In [61]:
i = i + 1

In [62]:
i

6

In [63]:
i += 1

In [64]:
i

7

---

In [17]:
## 실수형 할당
d = 174.5

In [18]:
type(d)

float

---

In [19]:
# 자료형 : 리스트
e = [a,b,c,d] 

In [20]:
e

['babo', 2018, '2018', 174.5]

In [22]:
f = ['name','year','str_year','height']

In [23]:
f

['name', 'year', 'str_year', 'height']

---

In [21]:
# 자료형 : 딕셔너리

In [27]:
list(zip(f,e)) # 두 리스트를 일렬로 나란이 붙인다. 

[('name', 'babo'), ('year', 2018), ('str_year', '2018'), ('height', 174.5)]

In [29]:
dict(zip(f,e))

{'height': 174.5, 'name': 'babo', 'str_year': '2018', 'year': 2018}

In [33]:
dic = dict(zip(f,e))

In [35]:
dic['height'],dic['name']

(174.5, 'babo')

---

In [36]:
# boolean 
b1 = True

In [37]:
b2 = False

In [38]:
b_list = [True,False,True]

In [42]:
1 == 1

True

In [43]:
b3 = 1 == 1

In [44]:
b3

True

---

In [45]:
# input 함수를 이용한 직접 입력받기 
name = input('name:')

In [46]:
age = eval(input('age:'))

In [47]:
print("Your name is %s and %d years old"%(name,age))

Your name is kang yang jae and 37 years old


---

In [50]:
# 조건문
age_kang = 37
age_jung = 50

if age_kang > age_jung:
    print("kang이 형")
elif age_jung > age_kang:
    print("jung이 형")
else:
    print("동갑")


jung이 형


In [ ]:
# 반복문

In [52]:
for i in [1,2,3,4,5]:
    print("숫자 : %d"%i)

숫자 : 1
숫자 : 2
숫자 : 3
숫자 : 4
숫자 : 5


In [54]:
i = 0 
for x in [1,2,3,4,5]:
    print("%d + %d = %d"%(i,x,i+x))
    i = i+x

0 + 1 = 1
1 + 2 = 3
3 + 3 = 6
6 + 4 = 10
10 + 5 = 15


In [55]:
i = 0
while i < 10:
    print("아직 %d <10"%i)
    i += 1

아직 0 <10
아직 1 <10
아직 2 <10
아직 3 <10
아직 4 <10
아직 5 <10
아직 6 <10
아직 7 <10
아직 8 <10
아직 9 <10


In [66]:
while 1:
    name = input("이름:")
    age  = eval(input("나이:"))
    if age == 0:
        break
    elif age >= 25:
        print("당신(%s)은 20대 후반 입니다."%name)
    else: print("당신(%s)은 20대 초반 입니다."%name)
        

![](https://i.pinimg.com/originals/2c/09/44/2c0944772f1ecbcc0e2068f342d5aa90.jpg)

In [67]:
genecode = {}
while 1:
    codon = input("codon : ")
    amino = input("amino acid : ")
    if codon == '' or amino == '':
        break
    else: genecode[codon] = amino


In [68]:
genecode

{'ATT': 'I'}

## 연습문제

- "This is sequence file"을 화면에 출력하시오.

- standard input으로 (즉,화면에서) 임의의 문자열 입력받아 화면에 출력하시오.

- 두 정수를 standard input으로 입력받아 변수 a와 b에 저장하고 이들의 합을 변수 c에 저장한 후 결과를 출력하시오.

- 두 수를 입력하고 둘 중에 큰 수를 출력해주는 프로그램을 작성하시오.

- Standard input으로 3-base codon을 입력받아서 아미노산으로 출력하시오.

- 4번의 문제에서 입력을 계속 받을 수 있도록 수정하시오.

---

In [83]:
# numpy 자료형
import numpy as np

In [71]:
a = np.array([1,2,3,4,5])

In [72]:
a

array([1, 2, 3, 4, 5])

In [93]:
# index 쓰는 법은 list 자료형과 닮아있다. 
a[0]

1

In [94]:
a[0:3]

array([1, 2, 3])

In [96]:
a[1:1+3]

array([2, 3, 4])

In [97]:
a[-2:] # 뒤에서 두번째 부터 끝까지 

array([4, 5])

In [98]:
a[::-1] # 어레이를 뒤집을때 자주 쓴다. 

array([5, 4, 3, 2, 1])

In [103]:
a[[1,3,4]] # 여러개를 선택할 수 있다. 

array([2, 4, 5])

In [105]:
# numpy array의 가장 큰 특징 Broadcasting 
a

array([1, 2, 3, 4, 5])

In [111]:
a * 2

array([ 2,  4,  6,  8, 10])

In [110]:
a * a * 2

array([ 2,  8, 18, 32, 50])

In [73]:
# 리스트 자료형과 닮았으나 기능이 매우 다르다. 
b = [1,2,3,4,5]

In [74]:
b

[1, 2, 3, 4, 5]

In [85]:
b*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [109]:
# array를 쌓아서 matrix를 만들어보자 
np.stack((a,a*2,a*a*2))

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 2,  8, 18, 32, 50]])

In [132]:
np.stack((a,a*2,a*a*2),axis=1) # axis 를 따로 지정하지 않으면 기본값으로 axis=0으로 간주 

array([[ 1,  2,  2],
       [ 2,  4,  8],
       [ 3,  6, 18],
       [ 4,  8, 32],
       [ 5, 10, 50]])

In [90]:
# numpy array를 쌓아서 matrix를 만들수 있다. 
mat = np.stack((a,a*2,a*(a*2)))

In [92]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 2,  8, 18, 32, 50]])

In [133]:
# transpose 기능 행렬을 바꾼다.  
mat.T

array([[ 1,  2,  2],
       [ 2,  4,  8],
       [ 3,  6, 18],
       [ 4,  8, 32],
       [ 5, 10, 50]])

In [115]:
mat.shape # 행이 3개 열이 5개 

(3, 5)

In [134]:
# matrix indexing
mat[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 2,  8, 18, 32, 50]])

In [135]:
mat[1,:]

array([ 2,  4,  6,  8, 10])

In [136]:
mat[2,:]

array([ 2,  8, 18, 32, 50])

In [137]:
mat[1:,:]

array([[ 2,  4,  6,  8, 10],
       [ 2,  8, 18, 32, 50]])

In [138]:
mat[:,1:]

array([[ 2,  3,  4,  5],
       [ 4,  6,  8, 10],
       [ 8, 18, 32, 50]])

In [139]:
# array masking
a_array = np.array([1,2,3,4,5])

In [140]:
a_array > 3

array([False, False, False,  True,  True])

In [141]:
mask = a_array > 3

In [142]:
mask

array([False, False, False,  True,  True])

In [143]:
a_array[mask]

array([4, 5])

In [160]:
mask2 = a_array < 5

In [161]:
a_array[mask&mask2]

array([4])

In [162]:
a_array[mask|mask2]

array([1, 2, 3, 4, 5])

In [144]:
# matrix masking
mat_mask = mat > 5

In [145]:
mat_mask

array([[False, False, False, False, False],
       [False, False,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [147]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 2,  8, 18, 32, 50]])

In [146]:
mat[mat_mask]

array([ 6,  8, 10,  8, 18, 32, 50])

In [150]:
m1 = mat[:,0]>1

In [152]:
m1

array([False,  True,  True])

In [154]:
mat[m1]

array([[ 2,  4,  6,  8, 10],
       [ 2,  8, 18, 32, 50]])

In [153]:
mat[m1,:]

array([[ 2,  4,  6,  8, 10],
       [ 2,  8, 18, 32, 50]])

In [155]:
m2 = mat[2,:] > 3

In [156]:
m2

array([False,  True,  True,  True,  True])

In [158]:
mat[:,m2]

array([[ 2,  3,  4,  5],
       [ 4,  6,  8, 10],
       [ 8, 18, 32, 50]])

In [159]:
mat[m2] # 행이아닌 열을 마스킹 할 경우에는 알아서 인식해주지 않는다. 

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 5

In [117]:
info1 = ['Kang','Yang Jae',37,174.5,68]
info2 = ['Hong','Gil Dong',20,160,66]

In [119]:
info_mat = np.stack((info1,info2))

In [80]:
import pandas as pd

In [122]:
df = pd.DataFrame(data=info_mat,columns=['LN','FN','AGE','HEIGHT','WEIGHT'])

In [123]:
df

LN        FN AGE HEIGHT WEIGHT
0  Kang  Yang Jae  37  174.5     68
1  Hong  Gil Dong  20    160     66

https://www.ebi.ac.uk/gxa/home

In [125]:
df_exp = pd.read_csv('tpms.tsv',sep='\t',comment='#')

In [126]:
df_exp.head()

Gene ID Gene Name  leaf  flower  fruit  root
0  AT1G01010    NAC001   4.0    10.0    3.0  38.0
1  AT1G01020      ARV1  16.0    16.0    7.0  18.0
2  AT1G01030      NGA3   5.0     7.0    1.0   2.0
3  AT1G01040      DCL1  16.0    21.0   16.0  19.0
4  AT1G01046   MIR838A   6.0     7.0    5.0   8.0

In [127]:
df_exp.shape

(28903, 6)

In [128]:
df_exp['Gene ID']

0        AT1G01010
1        AT1G01020
2        AT1G01030
3        AT1G01040
4        AT1G01046
5        AT1G01050
6        AT1G01060
7        AT1G01070
8        AT1G01080
9        AT1G01090
10       AT1G01100
11       AT1G01110
12       AT1G01120
13       AT1G01130
14       AT1G01140
15       AT1G01150
16       AT1G01160
17       AT1G01170
18       AT1G01180
19       AT1G01183
20       AT1G01190
21       AT1G01200
22       AT1G01210
23       AT1G01220
24       AT1G01225
25       AT1G01230
26       AT1G01240
27       AT1G01250
28       AT1G01260
29       AT1G01280
           ...    
28873    ATMG01060
28874    ATMG01090
28875    ATMG01100
28876    ATMG01120
28877    ATMG01130
28878    ATMG01170
28879    ATMG01180
28880    ATMG01190
28881    ATMG01200
28882    ATMG01210
28883    ATMG01220
28884    ATMG01230
28885    ATMG01240
28886    ATMG01250
28887    ATMG01260
28888    ATMG01280
28889    ATMG01290
28890    ATMG01320
28891    ATMG01330
28892    ATMG01350
28893    ATMG01360
28894    ATM

In [129]:
df_exp['Gene Name']

0              NAC001
1                ARV1
2                NGA3
3                DCL1
4             MIR838A
5                PPA1
6                 LHY
7           AT1G01070
8           AT1G01080
9        PDH-E1 ALPHA
10              RPP1A
11              IQD18
12               KCS1
13          AT1G01130
14              CIPK9
15          AT1G01150
16               GIF2
17          AT1G01170
18          AT1G01180
19            MIR165A
20            CYP78A8
21              RABA3
22          AT1G01210
23               FKGP
24          AT1G01225
25          AT1G01230
26          AT1G01240
27             ERF023
28             BHLH13
29           CYP703A2
             ...     
28873         ORF107G
28874          ORF262
28875         ORF105A
28876           NAD1B
28877         ORF106F
28878          ATP6-2
28879         ORF111B
28880            ATP1
28881          ORF294
28882         ORF101B
28883          ORF113
28884         ORF145B
28885         ORF100C
28886          ORF102
28887     

In [131]:
df_exp['leaf']

0          4.0
1         16.0
2          5.0
3         16.0
4          6.0
5         64.0
6         27.0
7          8.0
8         84.0
9        181.0
10       283.0
11         4.0
12        44.0
13         5.0
14        79.0
15         0.2
16        36.0
17       169.0
18        13.0
19         NaN
20         1.0
21         0.6
22        11.0
23        14.0
24         5.0
25        41.0
26        45.0
27         4.0
28        13.0
29         NaN
         ...  
28873      0.1
28874      0.1
28875      NaN
28876      0.4
28877      0.9
28878      0.3
28879      0.1
28880      NaN
28881      0.3
28882      0.2
28883      0.4
28884      NaN
28885      NaN
28886      0.1
28887      NaN
28888      NaN
28889      NaN
28890      0.2
28891      1.0
28892      0.1
28893      0.9
28894      2.0
28895      3.0
28896     65.0
28897      NaN
28898      0.1
28899      NaN
28900      NaN
28901      NaN
28902      NaN
Name: leaf, Length: 28903, dtype: float64

**Expression Atlas 에서 Human data "Expression data from 7 Human Melanomas" RNAseq 데이터를 다운 받고 dataframe 에 넣어보자**